# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DockWidgetStreaming.ui'
#
# Created: Thu Mar  6 20:55:38 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidgetStreaming(object):
    def setupUi(self, DockWidgetStreaming):
        DockWidgetStreaming.setObjectName(_fromUtf8("DockWidgetStreaming"))
        DockWidgetStreaming.resize(400, 444)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DockWidgetStreaming.sizePolicy().hasHeightForWidth())
        DockWidgetStreaming.setSizePolicy(sizePolicy)
        DockWidgetStreaming.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 386, 307))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.GroupBoxAudioConfig = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.GroupBoxAudioConfig.setObjectName(_fromUtf8("GroupBoxAudioConfig"))
        self.gridLayout_4 = QtGui.QGridLayout(self.GroupBoxAudioConfig)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.LabelAudioCodec = QtGui.QLabel(self.GroupBoxAudioConfig)
        self.LabelAudioCodec.setObjectName(_fromUtf8("LabelAudioCodec"))
        self.gridLayout_4.addWidget(self.LabelAudioCodec, 0, 0, 1, 1)
        self.LabelVideoCodec = QtGui.QLabel(self.GroupBoxAudioConfig)
        self.LabelVideoCodec.setObjectName(_fromUtf8("LabelVideoCodec"))
        self.gridLayout_4.addWidget(self.LabelVideoCodec, 1, 0, 1, 1)
        self.ComboBoxAudioCodec = QtGui.QComboBox(self.GroupBoxAudioConfig)
        self.ComboBoxAudioCodec.setObjectName(_fromUtf8("ComboBoxAudioCodec"))
        self.ComboBoxAudioCodec.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.ComboBoxAudioCodec, 0, 1, 1, 1)
        self.ComboBoxAudioBitrate = QtGui.QComboBox(self.GroupBoxAudioConfig)
        self.ComboBoxAudioBitrate.setObjectName(_fromUtf8("ComboBoxAudioBitrate"))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.ComboBoxAudioBitrate.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.ComboBoxAudioBitrate, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.GroupBoxAudioConfig)
        self.GroupBoxVideoConfig = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.GroupBoxVideoConfig.setObjectName(_fromUtf8("GroupBoxVideoConfig"))
        self.gridLayout_5 = QtGui.QGridLayout(self.GroupBoxVideoConfig)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.LabelVideoCodec_2 = QtGui.QLabel(self.GroupBoxVideoConfig)
        self.LabelVideoCodec_2.setObjectName(_fromUtf8("LabelVideoCodec_2"))
        self.gridLayout_5.addWidget(self.LabelVideoCodec_2, 0, 0, 1, 1)
        self.ComboBoxVideoCodec = QtGui.QComboBox(self.GroupBoxVideoConfig)
        self.ComboBoxVideoCodec.setObjectName(_fromUtf8("ComboBoxVideoCodec"))
        self.ComboBoxVideoCodec.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.ComboBoxVideoCodec, 0, 1, 1, 1)
        self.LabelVideoBitrate = QtGui.QLabel(self.GroupBoxVideoConfig)
        self.LabelVideoBitrate.setObjectName(_fromUtf8("LabelVideoBitrate"))
        self.gridLayout_5.addWidget(self.LabelVideoBitrate, 1, 0, 1, 1)
        self.SpinBoxVIdeoBitrate = QtGui.QSpinBox(self.GroupBoxVideoConfig)
        self.SpinBoxVIdeoBitrate.setMinimum(100)
        self.SpinBoxVIdeoBitrate.setMaximum(3000)
        self.SpinBoxVIdeoBitrate.setSingleStep(100)
        self.SpinBoxVIdeoBitrate.setObjectName(_fromUtf8("SpinBoxVIdeoBitrate"))
        self.gridLayout_5.addWidget(self.SpinBoxVIdeoBitrate, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.GroupBoxVideoConfig)
        self.GroupBoxConnection = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.GroupBoxConnection.setObjectName(_fromUtf8("GroupBoxConnection"))
        self.gridLayout_6 = QtGui.QGridLayout(self.GroupBoxConnection)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.LabelService = QtGui.QLabel(self.GroupBoxConnection)
        self.LabelService.setObjectName(_fromUtf8("LabelService"))
        self.gridLayout_6.addWidget(self.LabelService, 0, 0, 1, 1)
        self.ComboBoxService = QtGui.QComboBox(self.GroupBoxConnection)
        self.ComboBoxService.setObjectName(_fromUtf8("ComboBoxService"))
        self.ComboBoxService.addItem(_fromUtf8(""))
        self.ComboBoxService.addItem(_fromUtf8(""))
        self.ComboBoxService.addItem(_fromUtf8(""))
        self.ComboBoxService.addItem(_fromUtf8(""))
        self.ComboBoxService.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.ComboBoxService, 0, 1, 1, 1)
        self.LabelServerURL = QtGui.QLabel(self.GroupBoxConnection)
        self.LabelServerURL.setObjectName(_fromUtf8("LabelServerURL"))
        self.gridLayout_6.addWidget(self.LabelServerURL, 1, 0, 1, 1)
        self.LineEditServerURL = QtGui.QLineEdit(self.GroupBoxConnection)
        self.LineEditServerURL.setObjectName(_fromUtf8("LineEditServerURL"))
        self.gridLayout_6.addWidget(self.LineEditServerURL, 1, 1, 1, 1)
        self.LineEditServerKey = QtGui.QLineEdit(self.GroupBoxConnection)
        self.LineEditServerKey.setObjectName(_fromUtf8("LineEditServerKey"))
        self.gridLayout_6.addWidget(self.LineEditServerKey, 2, 1, 1, 1)
        self.LabelServerKey = QtGui.QLabel(self.GroupBoxConnection)
        self.LabelServerKey.setObjectName(_fromUtf8("LabelServerKey"))
        self.gridLayout_6.addWidget(self.LabelServerKey, 2, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.GroupBoxConnection)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.WidgetButtons = QtGui.QWidget(self.dockWidgetContents)
        self.WidgetButtons.setObjectName(_fromUtf8("WidgetButtons"))
        self.gridLayout_7 = QtGui.QGridLayout(self.WidgetButtons)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.ButtonPlay = QtGui.QPushButton(self.WidgetButtons)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-record"))
        self.ButtonPlay.setIcon(icon)
        self.ButtonPlay.setIconSize(QtCore.QSize(22, 22))
        self.ButtonPlay.setObjectName(_fromUtf8("ButtonPlay"))
        self.gridLayout_7.addWidget(self.ButtonPlay, 0, 0, 1, 1)
        self.ButtonStop = QtGui.QPushButton(self.WidgetButtons)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-stop"))
        self.ButtonStop.setIcon(icon)
        self.ButtonStop.setIconSize(QtCore.QSize(22, 22))
        self.ButtonStop.setObjectName(_fromUtf8("ButtonStop"))
        self.gridLayout_7.addWidget(self.ButtonStop, 0, 1, 1, 1)
        self.ButtonDot = QtGui.QPushButton(self.WidgetButtons)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-x-designer"))
        self.ButtonDot.setIcon(icon)
        self.ButtonDot.setIconSize(QtCore.QSize(22, 22))
        self.ButtonDot.setObjectName(_fromUtf8("ButtonDot"))
        self.gridLayout_7.addWidget(self.ButtonDot, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.WidgetButtons)
        self.ProgressBarStream = QtGui.QProgressBar(self.dockWidgetContents)
        self.ProgressBarStream.setMaximum(100)
        self.ProgressBarStream.setProperty("value", 0)
        self.ProgressBarStream.setTextVisible(False)
        self.ProgressBarStream.setOrientation(QtCore.Qt.Horizontal)
        self.ProgressBarStream.setObjectName(_fromUtf8("ProgressBarStream"))
        self.verticalLayout_2.addWidget(self.ProgressBarStream)
        DockWidgetStreaming.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidgetStreaming)
        QtCore.QMetaObject.connectSlotsByName(DockWidgetStreaming)

    def retranslateUi(self, DockWidgetStreaming):
        DockWidgetStreaming.setWindowTitle(_translate("DockWidgetStreaming", "Streaming", None))
        self.GroupBoxAudioConfig.setTitle(_translate("DockWidgetStreaming", "Configuración Audio", None))
        self.LabelAudioCodec.setText(_translate("DockWidgetStreaming", "Códec", None))
        self.LabelVideoCodec.setText(_translate("DockWidgetStreaming", "Bitrate (kbps)", None))
        self.ComboBoxAudioCodec.setItemText(0, _translate("DockWidgetStreaming", "AAC", None))
        self.ComboBoxAudioBitrate.setItemText(0, _translate("DockWidgetStreaming", "8", None))
        self.ComboBoxAudioBitrate.setItemText(1, _translate("DockWidgetStreaming", "16", None))
        self.ComboBoxAudioBitrate.setItemText(2, _translate("DockWidgetStreaming", "24", None))
        self.ComboBoxAudioBitrate.setItemText(3, _translate("DockWidgetStreaming", "32", None))
        self.ComboBoxAudioBitrate.setItemText(4, _translate("DockWidgetStreaming", "40", None))
        self.ComboBoxAudioBitrate.setItemText(5, _translate("DockWidgetStreaming", "48", None))
        self.ComboBoxAudioBitrate.setItemText(6, _translate("DockWidgetStreaming", "56", None))
        self.ComboBoxAudioBitrate.setItemText(7, _translate("DockWidgetStreaming", "64", None))
        self.ComboBoxAudioBitrate.setItemText(8, _translate("DockWidgetStreaming", "80", None))
        self.ComboBoxAudioBitrate.setItemText(9, _translate("DockWidgetStreaming", "96", None))
        self.ComboBoxAudioBitrate.setItemText(10, _translate("DockWidgetStreaming", "112", None))
        self.ComboBoxAudioBitrate.setItemText(11, _translate("DockWidgetStreaming", "128", None))
        self.ComboBoxAudioBitrate.setItemText(12, _translate("DockWidgetStreaming", "160", None))
        self.ComboBoxAudioBitrate.setItemText(13, _translate("DockWidgetStreaming", "192", None))
        self.ComboBoxAudioBitrate.setItemText(14, _translate("DockWidgetStreaming", "224", None))
        self.ComboBoxAudioBitrate.setItemText(15, _translate("DockWidgetStreaming", "256", None))
        self.ComboBoxAudioBitrate.setItemText(16, _translate("DockWidgetStreaming", "320", None))
        self.GroupBoxVideoConfig.setTitle(_translate("DockWidgetStreaming", "Configuración Video", None))
        self.LabelVideoCodec_2.setText(_translate("DockWidgetStreaming", "Códec", None))
        self.ComboBoxVideoCodec.setItemText(0, _translate("DockWidgetStreaming", "H264", None))
        self.LabelVideoBitrate.setText(_translate("DockWidgetStreaming", "Bitrate (kbps)", None))
        self.GroupBoxConnection.setTitle(_translate("DockWidgetStreaming", "Conexión", None))
        self.LabelService.setText(_translate("DockWidgetStreaming", "Servicio", None))
        self.ComboBoxService.setItemText(0, _translate("DockWidgetStreaming", "Castalba", None))
        self.ComboBoxService.setItemText(1, _translate("DockWidgetStreaming", "Ustream", None))
        self.ComboBoxService.setItemText(2, _translate("DockWidgetStreaming", "Justin", None))
        self.ComboBoxService.setItemText(3, _translate("DockWidgetStreaming", "Youtube", None))
        self.ComboBoxService.setItemText(4, _translate("DockWidgetStreaming", "Otro (personalizado)", None))
        self.LabelServerURL.setText(_translate("DockWidgetStreaming", "URL Servidor", None))
        self.LabelServerKey.setText(_translate("DockWidgetStreaming", "Key", None))
        self.ButtonPlay.setText(_translate("DockWidgetStreaming", "Emitir", None))
        self.ButtonStop.setText(_translate("DockWidgetStreaming", "Detener Emisión", None))
        self.ButtonDot.setText(_translate("DockWidgetStreaming", "Generar Dot", None))

