# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sun Mar  9 23:29:03 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 576)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 576))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.LayoutCentralWidget = QtGui.QHBoxLayout(self.centralwidget)
        self.LayoutCentralWidget.setObjectName(_fromUtf8("LayoutCentralWidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.Menubar = QtGui.QMenuBar(MainWindow)
        self.Menubar.setGeometry(QtCore.QRect(0, 0, 1024, 20))
        self.Menubar.setObjectName(_fromUtf8("Menubar"))
        self.MenuArchivo = QtGui.QMenu(self.Menubar)
        self.MenuArchivo.setObjectName(_fromUtf8("MenuArchivo"))
        self.MenuAyuda = QtGui.QMenu(self.Menubar)
        self.MenuAyuda.setObjectName(_fromUtf8("MenuAyuda"))
        MainWindow.setMenuBar(self.Menubar)
        self.ToolBar = QtGui.QToolBar(MainWindow)
        self.ToolBar.setMovable(True)
        self.ToolBar.setIconSize(QtCore.QSize(22, 22))
        self.ToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ToolBar.setFloatable(False)
        self.ToolBar.setObjectName(_fromUtf8("ToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.DockWidgetSources = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DockWidgetSources.sizePolicy().hasHeightForWidth())
        self.DockWidgetSources.setSizePolicy(sizePolicy)
        self.DockWidgetSources.setMinimumSize(QtCore.QSize(200, 200))
        self.DockWidgetSources.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.DockWidgetSources.setObjectName(_fromUtf8("DockWidgetSources"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ScrollAreaSources = QtGui.QScrollArea(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScrollAreaSources.sizePolicy().hasHeightForWidth())
        self.ScrollAreaSources.setSizePolicy(sizePolicy)
        self.ScrollAreaSources.setFrameShadow(QtGui.QFrame.Plain)
        self.ScrollAreaSources.setWidgetResizable(True)
        self.ScrollAreaSources.setObjectName(_fromUtf8("ScrollAreaSources"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 455))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.LayoutSources = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.LayoutSources.setObjectName(_fromUtf8("LayoutSources"))
        self.ScrollAreaSources.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.ScrollAreaSources)
        self.DockWidgetSources.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.DockWidgetSources)
        self.ActionQuit = QtGui.QAction(MainWindow)
        self.ActionQuit.setObjectName(_fromUtf8("ActionQuit"))
        self.ActionAbout = QtGui.QAction(MainWindow)
        self.ActionAbout.setObjectName(_fromUtf8("ActionAbout"))
        self.ActionWebcam = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("camera-web"))
        self.ActionWebcam.setIcon(icon)
        self.ActionWebcam.setObjectName(_fromUtf8("ActionWebcam"))
        self.ActionFile = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("applications-multimedia"))
        self.ActionFile.setIcon(icon)
        self.ActionFile.setObjectName(_fromUtf8("ActionFile"))
        self.ActionAndroid = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("pda"))
        self.ActionAndroid.setIcon(icon)
        self.ActionAndroid.setObjectName(_fromUtf8("ActionAndroid"))
        self.ActionMic = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("audio-input-microphone"))
        self.ActionMic.setIcon(icon)
        self.ActionMic.setObjectName(_fromUtf8("ActionMic"))
        self.ActionVideoAudiotest = QtGui.QAction(MainWindow)
        self.ActionVideoAudiotest.setObjectName(_fromUtf8("ActionVideoAudiotest"))
        self.ActionDesktopApp = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("computer"))
        self.ActionDesktopApp.setIcon(icon)
        self.ActionDesktopApp.setObjectName(_fromUtf8("ActionDesktopApp"))
        self.actionTemplateImport = QtGui.QAction(MainWindow)
        self.actionTemplateImport.setObjectName(_fromUtf8("actionTemplateImport"))
        self.actionTemplateExport = QtGui.QAction(MainWindow)
        self.actionTemplateExport.setObjectName(_fromUtf8("actionTemplateExport"))
        self.MenuArchivo.addAction(self.actionTemplateImport)
        self.MenuArchivo.addAction(self.actionTemplateExport)
        self.MenuArchivo.addAction(self.ActionQuit)
        self.MenuAyuda.addAction(self.ActionAbout)
        self.Menubar.addAction(self.MenuArchivo.menuAction())
        self.Menubar.addAction(self.MenuAyuda.menuAction())
        self.ToolBar.addAction(self.ActionVideoAudiotest)
        self.ToolBar.addAction(self.ActionFile)
        self.ToolBar.addAction(self.ActionWebcam)
        self.ToolBar.addAction(self.ActionAndroid)
        self.ToolBar.addAction(self.ActionMic)
        self.ToolBar.addAction(self.ActionDesktopApp)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HHTV Studio", None))
        self.MenuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.MenuAyuda.setTitle(_translate("MainWindow", "Ayuda", None))
        self.ToolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.DockWidgetSources.setWindowTitle(_translate("MainWindow", "Lista de Fuentes", None))
        self.ActionQuit.setText(_translate("MainWindow", "Salir", None))
        self.ActionAbout.setText(_translate("MainWindow", "Acerca de", None))
        self.ActionWebcam.setText(_translate("MainWindow", "Webcam", None))
        self.ActionWebcam.setToolTip(_translate("MainWindow", "Agregar Webcam", None))
        self.ActionFile.setText(_translate("MainWindow", "Archivo", None))
        self.ActionFile.setToolTip(_translate("MainWindow", "Agregar archivo de audio o video", None))
        self.ActionAndroid.setText(_translate("MainWindow", "Android", None))
        self.ActionAndroid.setToolTip(_translate("MainWindow", "Usando IP Webcam", None))
        self.ActionMic.setText(_translate("MainWindow", "Micrófono", None))
        self.ActionMic.setToolTip(_translate("MainWindow", "Añadir microfono", None))
        self.ActionVideoAudiotest.setText(_translate("MainWindow", "Audio / Video de prueba", None))
        self.ActionVideoAudiotest.setToolTip(_translate("MainWindow", "Agregar audio / video de prueba", None))
        self.ActionDesktopApp.setText(_translate("MainWindow", "Aplicación de Escritorio", None))
        self.actionTemplateImport.setText(_translate("MainWindow", "Importar desde plantilla", None))
        self.actionTemplateExport.setText(_translate("MainWindow", "Exportar a plantilla", None))

