# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_Generic.ui'
#
# Created: Fri Mar  7 00:00:49 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WidgetGeneric(object):
    def setupUi(self, WidgetGeneric):
        WidgetGeneric.setObjectName(_fromUtf8("WidgetGeneric"))
        WidgetGeneric.resize(582, 364)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetGeneric.sizePolicy().hasHeightForWidth())
        WidgetGeneric.setSizePolicy(sizePolicy)
        WidgetGeneric.setFrameShape(QtGui.QFrame.StyledPanel)
        WidgetGeneric.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout_4 = QtGui.QGridLayout(WidgetGeneric)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.GroupBoxGeneralSettings = QtGui.QGroupBox(WidgetGeneric)
        self.GroupBoxGeneralSettings.setMinimumSize(QtCore.QSize(0, 0))
        self.GroupBoxGeneralSettings.setObjectName(_fromUtf8("GroupBoxGeneralSettings"))
        self.LayoutGeneralSettings = QtGui.QGridLayout(self.GroupBoxGeneralSettings)
        self.LayoutGeneralSettings.setObjectName(_fromUtf8("LayoutGeneralSettings"))
        self.LineEditName = QtGui.QLineEdit(self.GroupBoxGeneralSettings)
        self.LineEditName.setMaxLength(20)
        self.LineEditName.setReadOnly(True)
        self.LineEditName.setObjectName(_fromUtf8("LineEditName"))
        self.LayoutGeneralSettings.addWidget(self.LineEditName, 0, 1, 1, 1)
        self.ButtonDelete = QtGui.QPushButton(self.GroupBoxGeneralSettings)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.ButtonDelete.setIcon(icon)
        self.ButtonDelete.setIconSize(QtCore.QSize(22, 22))
        self.ButtonDelete.setObjectName(_fromUtf8("ButtonDelete"))
        self.LayoutGeneralSettings.addWidget(self.ButtonDelete, 2, 1, 1, 1)
        self.LabelName = QtGui.QLabel(self.GroupBoxGeneralSettings)
        self.LabelName.setObjectName(_fromUtf8("LabelName"))
        self.LayoutGeneralSettings.addWidget(self.LabelName, 0, 0, 1, 1)
        self.ToolButtonEditName = QtGui.QToolButton(self.GroupBoxGeneralSettings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToolButtonEditName.sizePolicy().hasHeightForWidth())
        self.ToolButtonEditName.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-rename"))
        self.ToolButtonEditName.setIcon(icon)
        self.ToolButtonEditName.setIconSize(QtCore.QSize(22, 22))
        self.ToolButtonEditName.setCheckable(True)
        self.ToolButtonEditName.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ToolButtonEditName.setObjectName(_fromUtf8("ToolButtonEditName"))
        self.LayoutGeneralSettings.addWidget(self.ToolButtonEditName, 0, 2, 1, 2)
        self.gridLayout_4.addWidget(self.GroupBoxGeneralSettings, 0, 0, 1, 2)
        self.WidgetPreviewAndButtons = QtGui.QWidget(WidgetGeneric)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidgetPreviewAndButtons.sizePolicy().hasHeightForWidth())
        self.WidgetPreviewAndButtons.setSizePolicy(sizePolicy)
        self.WidgetPreviewAndButtons.setObjectName(_fromUtf8("WidgetPreviewAndButtons"))
        self.verticalLayout = QtGui.QVBoxLayout(self.WidgetPreviewAndButtons)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.WidgetPreview = QtGui.QWidget(self.WidgetPreviewAndButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidgetPreview.sizePolicy().hasHeightForWidth())
        self.WidgetPreview.setSizePolicy(sizePolicy)
        self.WidgetPreview.setMinimumSize(QtCore.QSize(170, 170))
        self.WidgetPreview.setObjectName(_fromUtf8("WidgetPreview"))
        self.verticalLayout.addWidget(self.WidgetPreview)
        self.WidgetButtons = QtGui.QWidget(self.WidgetPreviewAndButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidgetButtons.sizePolicy().hasHeightForWidth())
        self.WidgetButtons.setSizePolicy(sizePolicy)
        self.WidgetButtons.setObjectName(_fromUtf8("WidgetButtons"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.WidgetButtons)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ButtonPlay = QtGui.QPushButton(self.WidgetButtons)
        self.ButtonPlay.setObjectName(_fromUtf8("ButtonPlay"))
        self.horizontalLayout_3.addWidget(self.ButtonPlay)
        self.ButtonPause = QtGui.QPushButton(self.WidgetButtons)
        self.ButtonPause.setObjectName(_fromUtf8("ButtonPause"))
        self.horizontalLayout_3.addWidget(self.ButtonPause)
        self.ButtonStop = QtGui.QPushButton(self.WidgetButtons)
        self.ButtonStop.setObjectName(_fromUtf8("ButtonStop"))
        self.horizontalLayout_3.addWidget(self.ButtonStop)
        self.verticalLayout.addWidget(self.WidgetButtons)
        self.ButtonDot = QtGui.QPushButton(self.WidgetPreviewAndButtons)
        self.ButtonDot.setCheckable(False)
        self.ButtonDot.setObjectName(_fromUtf8("ButtonDot"))
        self.verticalLayout.addWidget(self.ButtonDot)
        self.gridLayout_4.addWidget(self.WidgetPreviewAndButtons, 1, 0, 1, 1)
        self.TabWidget = QtGui.QTabWidget(WidgetGeneric)
        self.TabWidget.setObjectName(_fromUtf8("TabWidget"))
        self.TabVideo = QtGui.QWidget()
        self.TabVideo.setObjectName(_fromUtf8("TabVideo"))
        self.LayoutVideoSettings = QtGui.QGridLayout(self.TabVideo)
        self.LayoutVideoSettings.setObjectName(_fromUtf8("LayoutVideoSettings"))
        self.LabelXposValue = QtGui.QLabel(self.TabVideo)
        self.LabelXposValue.setObjectName(_fromUtf8("LabelXposValue"))
        self.LayoutVideoSettings.addWidget(self.LabelXposValue, 5, 2, 1, 1)
        self.LabelYpos = QtGui.QLabel(self.TabVideo)
        self.LabelYpos.setObjectName(_fromUtf8("LabelYpos"))
        self.LayoutVideoSettings.addWidget(self.LabelYpos, 6, 0, 1, 1)
        self.SliderXpos = QtGui.QSlider(self.TabVideo)
        self.SliderXpos.setEnabled(True)
        self.SliderXpos.setMinimum(-2000)
        self.SliderXpos.setMaximum(2000)
        self.SliderXpos.setOrientation(QtCore.Qt.Horizontal)
        self.SliderXpos.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderXpos.setTickInterval(200)
        self.SliderXpos.setObjectName(_fromUtf8("SliderXpos"))
        self.LayoutVideoSettings.addWidget(self.SliderXpos, 5, 1, 1, 1)
        self.LabelAlphaValue = QtGui.QLabel(self.TabVideo)
        self.LabelAlphaValue.setObjectName(_fromUtf8("LabelAlphaValue"))
        self.LayoutVideoSettings.addWidget(self.LabelAlphaValue, 3, 2, 1, 1)
        self.SpinBoxFramerate = QtGui.QSpinBox(self.TabVideo)
        self.SpinBoxFramerate.setMinimum(1)
        self.SpinBoxFramerate.setMaximum(30)
        self.SpinBoxFramerate.setProperty("value", 30)
        self.SpinBoxFramerate.setObjectName(_fromUtf8("SpinBoxFramerate"))
        self.LayoutVideoSettings.addWidget(self.SpinBoxFramerate, 2, 1, 1, 2)
        self.LabelYposValue = QtGui.QLabel(self.TabVideo)
        self.LabelYposValue.setObjectName(_fromUtf8("LabelYposValue"))
        self.LayoutVideoSettings.addWidget(self.LabelYposValue, 6, 2, 1, 1)
        self.SliderHeight = QtGui.QSlider(self.TabVideo)
        self.SliderHeight.setMinimum(10)
        self.SliderHeight.setMaximum(1280)
        self.SliderHeight.setSingleStep(2)
        self.SliderHeight.setProperty("value", 300)
        self.SliderHeight.setOrientation(QtCore.Qt.Horizontal)
        self.SliderHeight.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderHeight.setTickInterval(50)
        self.SliderHeight.setObjectName(_fromUtf8("SliderHeight"))
        self.LayoutVideoSettings.addWidget(self.SliderHeight, 1, 1, 1, 1)
        self.SliderAlpha = QtGui.QSlider(self.TabVideo)
        self.SliderAlpha.setEnabled(True)
        self.SliderAlpha.setMaximum(100)
        self.SliderAlpha.setProperty("value", 100)
        self.SliderAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.SliderAlpha.setObjectName(_fromUtf8("SliderAlpha"))
        self.LayoutVideoSettings.addWidget(self.SliderAlpha, 3, 1, 1, 1)
        self.LabelWidthValue = QtGui.QLabel(self.TabVideo)
        self.LabelWidthValue.setObjectName(_fromUtf8("LabelWidthValue"))
        self.LayoutVideoSettings.addWidget(self.LabelWidthValue, 0, 2, 1, 1)
        self.LabelFramerate = QtGui.QLabel(self.TabVideo)
        self.LabelFramerate.setObjectName(_fromUtf8("LabelFramerate"))
        self.LayoutVideoSettings.addWidget(self.LabelFramerate, 2, 0, 1, 1)
        self.SliderYpos = QtGui.QSlider(self.TabVideo)
        self.SliderYpos.setEnabled(True)
        self.SliderYpos.setMinimum(-2000)
        self.SliderYpos.setMaximum(2000)
        self.SliderYpos.setOrientation(QtCore.Qt.Horizontal)
        self.SliderYpos.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderYpos.setTickInterval(200)
        self.SliderYpos.setObjectName(_fromUtf8("SliderYpos"))
        self.LayoutVideoSettings.addWidget(self.SliderYpos, 6, 1, 1, 1)
        self.LabelHeightValue = QtGui.QLabel(self.TabVideo)
        self.LabelHeightValue.setObjectName(_fromUtf8("LabelHeightValue"))
        self.LayoutVideoSettings.addWidget(self.LabelHeightValue, 1, 2, 1, 1)
        self.LabelHeight = QtGui.QLabel(self.TabVideo)
        self.LabelHeight.setObjectName(_fromUtf8("LabelHeight"))
        self.LayoutVideoSettings.addWidget(self.LabelHeight, 1, 0, 1, 1)
        self.SliderWidth = QtGui.QSlider(self.TabVideo)
        self.SliderWidth.setMinimum(10)
        self.SliderWidth.setMaximum(1280)
        self.SliderWidth.setSingleStep(2)
        self.SliderWidth.setProperty("value", 400)
        self.SliderWidth.setOrientation(QtCore.Qt.Horizontal)
        self.SliderWidth.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderWidth.setTickInterval(50)
        self.SliderWidth.setObjectName(_fromUtf8("SliderWidth"))
        self.LayoutVideoSettings.addWidget(self.SliderWidth, 0, 1, 1, 1)
        self.LabelWidth = QtGui.QLabel(self.TabVideo)
        self.LabelWidth.setObjectName(_fromUtf8("LabelWidth"))
        self.LayoutVideoSettings.addWidget(self.LabelWidth, 0, 0, 1, 1)
        self.LabelXpos = QtGui.QLabel(self.TabVideo)
        self.LabelXpos.setObjectName(_fromUtf8("LabelXpos"))
        self.LayoutVideoSettings.addWidget(self.LabelXpos, 5, 0, 1, 1)
        self.LabelAlpha = QtGui.QLabel(self.TabVideo)
        self.LabelAlpha.setObjectName(_fromUtf8("LabelAlpha"))
        self.LayoutVideoSettings.addWidget(self.LabelAlpha, 3, 0, 1, 1)
        self.LabelZpos = QtGui.QLabel(self.TabVideo)
        self.LabelZpos.setObjectName(_fromUtf8("LabelZpos"))
        self.LayoutVideoSettings.addWidget(self.LabelZpos, 7, 0, 1, 1)
        self.SpinBoxZpos = QtGui.QSpinBox(self.TabVideo)
        self.SpinBoxZpos.setMinimum(1)
        self.SpinBoxZpos.setMaximum(10)
        self.SpinBoxZpos.setObjectName(_fromUtf8("SpinBoxZpos"))
        self.LayoutVideoSettings.addWidget(self.SpinBoxZpos, 7, 1, 1, 2)
        self.TabWidget.addTab(self.TabVideo, _fromUtf8(""))
        self.TabAudio = QtGui.QWidget()
        self.TabAudio.setObjectName(_fromUtf8("TabAudio"))
        self.LayoutAudioSettings = QtGui.QGridLayout(self.TabAudio)
        self.LayoutAudioSettings.setObjectName(_fromUtf8("LayoutAudioSettings"))
        self.TabWidget.addTab(self.TabAudio, _fromUtf8(""))
        self.TabText = QtGui.QWidget()
        self.TabText.setObjectName(_fromUtf8("TabText"))
        self.LayoutTextSettings = QtGui.QGridLayout(self.TabText)
        self.LayoutTextSettings.setObjectName(_fromUtf8("LayoutTextSettings"))
        self.CheckBoxText = QtGui.QCheckBox(self.TabText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBoxText.sizePolicy().hasHeightForWidth())
        self.CheckBoxText.setSizePolicy(sizePolicy)
        self.CheckBoxText.setObjectName(_fromUtf8("CheckBoxText"))
        self.LayoutTextSettings.addWidget(self.CheckBoxText, 0, 1, 1, 1)
        self.LabelText = QtGui.QLabel(self.TabText)
        self.LabelText.setObjectName(_fromUtf8("LabelText"))
        self.LayoutTextSettings.addWidget(self.LabelText, 1, 0, 1, 1)
        self.LineEditText = QtGui.QLineEdit(self.TabText)
        self.LineEditText.setEnabled(False)
        self.LineEditText.setMaxLength(100)
        self.LineEditText.setObjectName(_fromUtf8("LineEditText"))
        self.LayoutTextSettings.addWidget(self.LineEditText, 1, 1, 1, 3)
        self.LabelXposText = QtGui.QLabel(self.TabText)
        self.LabelXposText.setObjectName(_fromUtf8("LabelXposText"))
        self.LayoutTextSettings.addWidget(self.LabelXposText, 2, 0, 1, 1)
        self.SliderXposText = QtGui.QSlider(self.TabText)
        self.SliderXposText.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderXposText.sizePolicy().hasHeightForWidth())
        self.SliderXposText.setSizePolicy(sizePolicy)
        self.SliderXposText.setMaximum(100)
        self.SliderXposText.setOrientation(QtCore.Qt.Horizontal)
        self.SliderXposText.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderXposText.setTickInterval(10)
        self.SliderXposText.setObjectName(_fromUtf8("SliderXposText"))
        self.LayoutTextSettings.addWidget(self.SliderXposText, 2, 1, 1, 3)
        self.LabelXposValueText = QtGui.QLabel(self.TabText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelXposValueText.sizePolicy().hasHeightForWidth())
        self.LabelXposValueText.setSizePolicy(sizePolicy)
        self.LabelXposValueText.setObjectName(_fromUtf8("LabelXposValueText"))
        self.LayoutTextSettings.addWidget(self.LabelXposValueText, 2, 4, 1, 1)
        self.LabelYposText = QtGui.QLabel(self.TabText)
        self.LabelYposText.setObjectName(_fromUtf8("LabelYposText"))
        self.LayoutTextSettings.addWidget(self.LabelYposText, 3, 0, 1, 1)
        self.SliderYposText = QtGui.QSlider(self.TabText)
        self.SliderYposText.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderYposText.sizePolicy().hasHeightForWidth())
        self.SliderYposText.setSizePolicy(sizePolicy)
        self.SliderYposText.setMaximum(100)
        self.SliderYposText.setOrientation(QtCore.Qt.Horizontal)
        self.SliderYposText.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderYposText.setTickInterval(10)
        self.SliderYposText.setObjectName(_fromUtf8("SliderYposText"))
        self.LayoutTextSettings.addWidget(self.SliderYposText, 3, 1, 1, 3)
        self.LabelYposValueText = QtGui.QLabel(self.TabText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelYposValueText.sizePolicy().hasHeightForWidth())
        self.LabelYposValueText.setSizePolicy(sizePolicy)
        self.LabelYposValueText.setObjectName(_fromUtf8("LabelYposValueText"))
        self.LayoutTextSettings.addWidget(self.LabelYposValueText, 3, 4, 1, 1)
        self.LabelFont = QtGui.QLabel(self.TabText)
        self.LabelFont.setObjectName(_fromUtf8("LabelFont"))
        self.LayoutTextSettings.addWidget(self.LabelFont, 4, 0, 1, 1)
        self.FontComboBox = QtGui.QFontComboBox(self.TabText)
        self.FontComboBox.setEnabled(False)
        self.FontComboBox.setFontFilters(QtGui.QFontComboBox.AllFonts)
        self.FontComboBox.setObjectName(_fromUtf8("FontComboBox"))
        self.LayoutTextSettings.addWidget(self.FontComboBox, 4, 1, 1, 3)
        self.LabelTextSize = QtGui.QLabel(self.TabText)
        self.LabelTextSize.setObjectName(_fromUtf8("LabelTextSize"))
        self.LayoutTextSettings.addWidget(self.LabelTextSize, 5, 0, 1, 1)
        self.SpinBoxTextSize = QtGui.QSpinBox(self.TabText)
        self.SpinBoxTextSize.setEnabled(False)
        self.SpinBoxTextSize.setMinimum(8)
        self.SpinBoxTextSize.setMaximum(72)
        self.SpinBoxTextSize.setObjectName(_fromUtf8("SpinBoxTextSize"))
        self.LayoutTextSettings.addWidget(self.SpinBoxTextSize, 5, 1, 1, 1)
        self.LabelStyle = QtGui.QLabel(self.TabText)
        self.LabelStyle.setObjectName(_fromUtf8("LabelStyle"))
        self.LayoutTextSettings.addWidget(self.LabelStyle, 5, 2, 1, 1)
        self.ComboBoxStyle = QtGui.QComboBox(self.TabText)
        self.ComboBoxStyle.setEnabled(False)
        self.ComboBoxStyle.setObjectName(_fromUtf8("ComboBoxStyle"))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.LayoutTextSettings.addWidget(self.ComboBoxStyle, 5, 3, 1, 1)
        self.TabWidget.addTab(self.TabText, _fromUtf8(""))
        self.TabNoProperties = QtGui.QWidget()
        self.TabNoProperties.setObjectName(_fromUtf8("TabNoProperties"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.TabNoProperties)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.TabNoProperties)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.TabWidget.addTab(self.TabNoProperties, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.TabWidget, 1, 1, 1, 1)

        self.retranslateUi(WidgetGeneric)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WidgetGeneric)

    def retranslateUi(self, WidgetGeneric):
        WidgetGeneric.setWindowTitle(_translate("WidgetGeneric", "Frame", None))
        self.GroupBoxGeneralSettings.setTitle(_translate("WidgetGeneric", "Propiedades Generales", None))
        self.ButtonDelete.setText(_translate("WidgetGeneric", "Eliminar ", None))
        self.LabelName.setText(_translate("WidgetGeneric", "Nombre", None))
        self.ToolButtonEditName.setText(_translate("WidgetGeneric", "Editar", None))
        self.ButtonPlay.setText(_translate("WidgetGeneric", "Play", None))
        self.ButtonPause.setText(_translate("WidgetGeneric", "Pause", None))
        self.ButtonStop.setText(_translate("WidgetGeneric", "Stop", None))
        self.ButtonDot.setText(_translate("WidgetGeneric", "Generar Dot", None))
        self.LabelXposValue.setText(_translate("WidgetGeneric", "0", None))
        self.LabelYpos.setText(_translate("WidgetGeneric", "Ypos", None))
        self.LabelAlphaValue.setText(_translate("WidgetGeneric", "100", None))
        self.LabelYposValue.setText(_translate("WidgetGeneric", "0", None))
        self.LabelWidthValue.setText(_translate("WidgetGeneric", "400", None))
        self.LabelFramerate.setText(_translate("WidgetGeneric", "Framerate", None))
        self.LabelHeightValue.setText(_translate("WidgetGeneric", "300", None))
        self.LabelHeight.setText(_translate("WidgetGeneric", "Heigth", None))
        self.LabelWidth.setText(_translate("WidgetGeneric", "Width", None))
        self.LabelXpos.setText(_translate("WidgetGeneric", "Xpos", None))
        self.LabelAlpha.setText(_translate("WidgetGeneric", "Canal Alpha", None))
        self.LabelZpos.setText(_translate("WidgetGeneric", "Zpos", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabVideo), _translate("WidgetGeneric", "Video", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabAudio), _translate("WidgetGeneric", "Audio", None))
        self.CheckBoxText.setText(_translate("WidgetGeneric", "Mostrar Texto", None))
        self.LabelText.setText(_translate("WidgetGeneric", "Texto", None))
        self.LineEditText.setText(_translate("WidgetGeneric", "texto", None))
        self.LabelXposText.setText(_translate("WidgetGeneric", "Xpos", None))
        self.LabelXposValueText.setText(_translate("WidgetGeneric", "0", None))
        self.LabelYposText.setText(_translate("WidgetGeneric", "Ypos", None))
        self.LabelYposValueText.setText(_translate("WidgetGeneric", "0", None))
        self.LabelFont.setText(_translate("WidgetGeneric", "Fuente", None))
        self.LabelTextSize.setText(_translate("WidgetGeneric", "Tamaño", None))
        self.LabelStyle.setText(_translate("WidgetGeneric", "Estilo", None))
        self.ComboBoxStyle.setItemText(0, _translate("WidgetGeneric", "Normal", None))
        self.ComboBoxStyle.setItemText(1, _translate("WidgetGeneric", "Negrita", None))
        self.ComboBoxStyle.setItemText(2, _translate("WidgetGeneric", "Cursiva", None))
        self.ComboBoxStyle.setItemText(3, _translate("WidgetGeneric", "Negrita y Cursiva", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabText), _translate("WidgetGeneric", "Texto", None))
        self.label.setText(_translate("WidgetGeneric", "No existen propiedades", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabNoProperties), _translate("WidgetGeneric", "Propiedades", None))

