# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frame_Mixer.ui'
#
# Created: Thu Mar  6 21:08:11 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WidgetMixer(object):
    def setupUi(self, WidgetMixer):
        WidgetMixer.setObjectName(_fromUtf8("WidgetMixer"))
        WidgetMixer.resize(666, 332)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WidgetMixer.sizePolicy().hasHeightForWidth())
        WidgetMixer.setSizePolicy(sizePolicy)
        WidgetMixer.setFrameShape(QtGui.QFrame.StyledPanel)
        WidgetMixer.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout_4 = QtGui.QGridLayout(WidgetMixer)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.GroupBoxGeneralSettings = QtGui.QGroupBox(WidgetMixer)
        self.GroupBoxGeneralSettings.setMinimumSize(QtCore.QSize(0, 0))
        self.GroupBoxGeneralSettings.setObjectName(_fromUtf8("GroupBoxGeneralSettings"))
        self.LayoutGeneralSettings = QtGui.QGridLayout(self.GroupBoxGeneralSettings)
        self.LayoutGeneralSettings.setObjectName(_fromUtf8("LayoutGeneralSettings"))
        self.LineEditName = QtGui.QLineEdit(self.GroupBoxGeneralSettings)
        self.LineEditName.setMaxLength(20)
        self.LineEditName.setReadOnly(True)
        self.LineEditName.setObjectName(_fromUtf8("LineEditName"))
        self.LayoutGeneralSettings.addWidget(self.LineEditName, 0, 1, 1, 1)
        self.LabelName = QtGui.QLabel(self.GroupBoxGeneralSettings)
        self.LabelName.setObjectName(_fromUtf8("LabelName"))
        self.LayoutGeneralSettings.addWidget(self.LabelName, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.GroupBoxGeneralSettings, 0, 0, 1, 2)
        self.widget_3 = QtGui.QWidget(WidgetMixer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.WidgetPreview = QtGui.QWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidgetPreview.sizePolicy().hasHeightForWidth())
        self.WidgetPreview.setSizePolicy(sizePolicy)
        self.WidgetPreview.setMinimumSize(QtCore.QSize(170, 170))
        self.WidgetPreview.setObjectName(_fromUtf8("WidgetPreview"))
        self.verticalLayout.addWidget(self.WidgetPreview)
        self.WidgetButtons = QtGui.QWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidgetButtons.sizePolicy().hasHeightForWidth())
        self.WidgetButtons.setSizePolicy(sizePolicy)
        self.WidgetButtons.setObjectName(_fromUtf8("WidgetButtons"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.WidgetButtons)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.ButtonPlay = QtGui.QPushButton(self.WidgetButtons)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.ButtonPlay.setIcon(icon)
        self.ButtonPlay.setIconSize(QtCore.QSize(22, 22))
        self.ButtonPlay.setObjectName(_fromUtf8("ButtonPlay"))
        self.horizontalLayout_3.addWidget(self.ButtonPlay)
        self.ButtonPause = QtGui.QPushButton(self.WidgetButtons)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-pause"))
        self.ButtonPause.setIcon(icon)
        self.ButtonPause.setIconSize(QtCore.QSize(22, 22))
        self.ButtonPause.setObjectName(_fromUtf8("ButtonPause"))
        self.horizontalLayout_3.addWidget(self.ButtonPause)
        self.ButtonStop = QtGui.QPushButton(self.WidgetButtons)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-stop"))
        self.ButtonStop.setIcon(icon)
        self.ButtonStop.setIconSize(QtCore.QSize(22, 22))
        self.ButtonStop.setObjectName(_fromUtf8("ButtonStop"))
        self.horizontalLayout_3.addWidget(self.ButtonStop)
        self.verticalLayout.addWidget(self.WidgetButtons)
        self.ButtonDot = QtGui.QPushButton(self.widget_3)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-x-designer"))
        self.ButtonDot.setIcon(icon)
        self.ButtonDot.setIconSize(QtCore.QSize(22, 22))
        self.ButtonDot.setCheckable(False)
        self.ButtonDot.setObjectName(_fromUtf8("ButtonDot"))
        self.verticalLayout.addWidget(self.ButtonDot)
        self.gridLayout_4.addWidget(self.widget_3, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(WidgetMixer)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.TabVideo = QtGui.QWidget()
        self.TabVideo.setObjectName(_fromUtf8("TabVideo"))
        self.gridLayout_2 = QtGui.QGridLayout(self.TabVideo)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.TabVideo)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 352, 219))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.LabelVideoSize = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.LabelVideoSize.setObjectName(_fromUtf8("LabelVideoSize"))
        self.gridLayout.addWidget(self.LabelVideoSize, 0, 0, 1, 1)
        self.ComboBoxVideoSize = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBoxVideoSize.setObjectName(_fromUtf8("ComboBoxVideoSize"))
        self.ComboBoxVideoSize.addItem(_fromUtf8(""))
        self.ComboBoxVideoSize.addItem(_fromUtf8(""))
        self.ComboBoxVideoSize.addItem(_fromUtf8(""))
        self.ComboBoxVideoSize.addItem(_fromUtf8(""))
        self.ComboBoxVideoSize.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ComboBoxVideoSize, 0, 1, 1, 2)
        self.LabelFramerate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.LabelFramerate.setObjectName(_fromUtf8("LabelFramerate"))
        self.gridLayout.addWidget(self.LabelFramerate, 1, 0, 1, 1)
        self.LabelAlpha = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.LabelAlpha.setObjectName(_fromUtf8("LabelAlpha"))
        self.gridLayout.addWidget(self.LabelAlpha, 2, 0, 1, 1)
        self.SliderAlpha = QtGui.QSlider(self.scrollAreaWidgetContents)
        self.SliderAlpha.setEnabled(True)
        self.SliderAlpha.setMaximum(100)
        self.SliderAlpha.setProperty("value", 0)
        self.SliderAlpha.setOrientation(QtCore.Qt.Horizontal)
        self.SliderAlpha.setObjectName(_fromUtf8("SliderAlpha"))
        self.gridLayout.addWidget(self.SliderAlpha, 2, 1, 1, 1)
        self.LabelAlphaValue = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.LabelAlphaValue.setObjectName(_fromUtf8("LabelAlphaValue"))
        self.gridLayout.addWidget(self.LabelAlphaValue, 2, 2, 1, 1)
        self.LabelAlphaMethod = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.LabelAlphaMethod.setObjectName(_fromUtf8("LabelAlphaMethod"))
        self.gridLayout.addWidget(self.LabelAlphaMethod, 3, 0, 1, 1)
        self.SpinBoxFramerate = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.SpinBoxFramerate.setMinimum(1)
        self.SpinBoxFramerate.setMaximum(30)
        self.SpinBoxFramerate.setProperty("value", 30)
        self.SpinBoxFramerate.setObjectName(_fromUtf8("SpinBoxFramerate"))
        self.gridLayout.addWidget(self.SpinBoxFramerate, 1, 1, 1, 2)
        self.ComboBoxAlphaMethod = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.ComboBoxAlphaMethod.setObjectName(_fromUtf8("ComboBoxAlphaMethod"))
        self.ComboBoxAlphaMethod.addItem(_fromUtf8(""))
        self.ComboBoxAlphaMethod.addItem(_fromUtf8(""))
        self.ComboBoxAlphaMethod.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ComboBoxAlphaMethod, 3, 1, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TabVideo, _fromUtf8(""))
        self.TabText = QtGui.QWidget()
        self.TabText.setObjectName(_fromUtf8("TabText"))
        self.LayoutTextSettings = QtGui.QGridLayout(self.TabText)
        self.LayoutTextSettings.setObjectName(_fromUtf8("LayoutTextSettings"))
        self.CheckBoxText = QtGui.QCheckBox(self.TabText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBoxText.sizePolicy().hasHeightForWidth())
        self.CheckBoxText.setSizePolicy(sizePolicy)
        self.CheckBoxText.setObjectName(_fromUtf8("CheckBoxText"))
        self.LayoutTextSettings.addWidget(self.CheckBoxText, 0, 1, 1, 1)
        self.LabelText = QtGui.QLabel(self.TabText)
        self.LabelText.setObjectName(_fromUtf8("LabelText"))
        self.LayoutTextSettings.addWidget(self.LabelText, 1, 0, 1, 1)
        self.LineEditText = QtGui.QLineEdit(self.TabText)
        self.LineEditText.setEnabled(False)
        self.LineEditText.setMaxLength(100)
        self.LineEditText.setObjectName(_fromUtf8("LineEditText"))
        self.LayoutTextSettings.addWidget(self.LineEditText, 1, 1, 1, 3)
        self.LabelXposText = QtGui.QLabel(self.TabText)
        self.LabelXposText.setObjectName(_fromUtf8("LabelXposText"))
        self.LayoutTextSettings.addWidget(self.LabelXposText, 2, 0, 1, 1)
        self.SliderXposText = QtGui.QSlider(self.TabText)
        self.SliderXposText.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderXposText.sizePolicy().hasHeightForWidth())
        self.SliderXposText.setSizePolicy(sizePolicy)
        self.SliderXposText.setMaximum(100)
        self.SliderXposText.setOrientation(QtCore.Qt.Horizontal)
        self.SliderXposText.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderXposText.setTickInterval(10)
        self.SliderXposText.setObjectName(_fromUtf8("SliderXposText"))
        self.LayoutTextSettings.addWidget(self.SliderXposText, 2, 1, 1, 3)
        self.LabelXposValueText = QtGui.QLabel(self.TabText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelXposValueText.sizePolicy().hasHeightForWidth())
        self.LabelXposValueText.setSizePolicy(sizePolicy)
        self.LabelXposValueText.setObjectName(_fromUtf8("LabelXposValueText"))
        self.LayoutTextSettings.addWidget(self.LabelXposValueText, 2, 4, 1, 1)
        self.LabelYposText = QtGui.QLabel(self.TabText)
        self.LabelYposText.setObjectName(_fromUtf8("LabelYposText"))
        self.LayoutTextSettings.addWidget(self.LabelYposText, 3, 0, 1, 1)
        self.SliderYposText = QtGui.QSlider(self.TabText)
        self.SliderYposText.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderYposText.sizePolicy().hasHeightForWidth())
        self.SliderYposText.setSizePolicy(sizePolicy)
        self.SliderYposText.setMaximum(100)
        self.SliderYposText.setOrientation(QtCore.Qt.Horizontal)
        self.SliderYposText.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SliderYposText.setTickInterval(10)
        self.SliderYposText.setObjectName(_fromUtf8("SliderYposText"))
        self.LayoutTextSettings.addWidget(self.SliderYposText, 3, 1, 1, 3)
        self.LabelYposValueText = QtGui.QLabel(self.TabText)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelYposValueText.sizePolicy().hasHeightForWidth())
        self.LabelYposValueText.setSizePolicy(sizePolicy)
        self.LabelYposValueText.setObjectName(_fromUtf8("LabelYposValueText"))
        self.LayoutTextSettings.addWidget(self.LabelYposValueText, 3, 4, 1, 1)
        self.LabelFont = QtGui.QLabel(self.TabText)
        self.LabelFont.setObjectName(_fromUtf8("LabelFont"))
        self.LayoutTextSettings.addWidget(self.LabelFont, 4, 0, 1, 1)
        self.FontComboBox = QtGui.QFontComboBox(self.TabText)
        self.FontComboBox.setEnabled(False)
        self.FontComboBox.setFontFilters(QtGui.QFontComboBox.AllFonts)
        self.FontComboBox.setObjectName(_fromUtf8("FontComboBox"))
        self.LayoutTextSettings.addWidget(self.FontComboBox, 4, 1, 1, 3)
        self.LabelTextSize = QtGui.QLabel(self.TabText)
        self.LabelTextSize.setObjectName(_fromUtf8("LabelTextSize"))
        self.LayoutTextSettings.addWidget(self.LabelTextSize, 5, 0, 1, 1)
        self.SpinBoxTextSize = QtGui.QSpinBox(self.TabText)
        self.SpinBoxTextSize.setEnabled(False)
        self.SpinBoxTextSize.setMinimum(8)
        self.SpinBoxTextSize.setMaximum(72)
        self.SpinBoxTextSize.setObjectName(_fromUtf8("SpinBoxTextSize"))
        self.LayoutTextSettings.addWidget(self.SpinBoxTextSize, 5, 1, 1, 1)
        self.LabelStyle = QtGui.QLabel(self.TabText)
        self.LabelStyle.setObjectName(_fromUtf8("LabelStyle"))
        self.LayoutTextSettings.addWidget(self.LabelStyle, 5, 2, 1, 1)
        self.ComboBoxStyle = QtGui.QComboBox(self.TabText)
        self.ComboBoxStyle.setEnabled(False)
        self.ComboBoxStyle.setObjectName(_fromUtf8("ComboBoxStyle"))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.ComboBoxStyle.addItem(_fromUtf8(""))
        self.LayoutTextSettings.addWidget(self.ComboBoxStyle, 5, 3, 1, 1)
        self.tabWidget.addTab(self.TabText, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 1, 1, 1, 1)

        self.retranslateUi(WidgetMixer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WidgetMixer)

    def retranslateUi(self, WidgetMixer):
        WidgetMixer.setWindowTitle(_translate("WidgetMixer", "Frame", None))
        self.GroupBoxGeneralSettings.setTitle(_translate("WidgetMixer", "Propiedades Generales", None))
        self.LineEditName.setText(_translate("WidgetMixer", "Mixer", None))
        self.LabelName.setText(_translate("WidgetMixer", "Nombre", None))
        self.ButtonPlay.setText(_translate("WidgetMixer", "Play", None))
        self.ButtonPause.setText(_translate("WidgetMixer", "Pause", None))
        self.ButtonStop.setText(_translate("WidgetMixer", "Stop", None))
        self.ButtonDot.setText(_translate("WidgetMixer", "Generar Dot", None))
        self.LabelVideoSize.setText(_translate("WidgetMixer", "Tamaño", None))
        self.ComboBoxVideoSize.setItemText(0, _translate("WidgetMixer", "640 x 480 (4:3)", None))
        self.ComboBoxVideoSize.setItemText(1, _translate("WidgetMixer", "800 x 600 (4:3)", None))
        self.ComboBoxVideoSize.setItemText(2, _translate("WidgetMixer", "1024 x 768 (4:3)", None))
        self.ComboBoxVideoSize.setItemText(3, _translate("WidgetMixer", "1024 x 576 (16:9)", None))
        self.ComboBoxVideoSize.setItemText(4, _translate("WidgetMixer", "1280 x 720 (16:9)", None))
        self.LabelFramerate.setText(_translate("WidgetMixer", "Framerate", None))
        self.LabelAlpha.setText(_translate("WidgetMixer", "Canal Alpha", None))
        self.LabelAlphaValue.setText(_translate("WidgetMixer", "0", None))
        self.LabelAlphaMethod.setText(_translate("WidgetMixer", "Método C. Alpha", None))
        self.ComboBoxAlphaMethod.setItemText(0, _translate("WidgetMixer", "Ninguno", None))
        self.ComboBoxAlphaMethod.setItemText(1, _translate("WidgetMixer", "Verde", None))
        self.ComboBoxAlphaMethod.setItemText(2, _translate("WidgetMixer", "Azul", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabVideo), _translate("WidgetMixer", "Video", None))
        self.CheckBoxText.setText(_translate("WidgetMixer", "Mostrar Texto", None))
        self.LabelText.setText(_translate("WidgetMixer", "Texto", None))
        self.LineEditText.setText(_translate("WidgetMixer", "texto", None))
        self.LabelXposText.setText(_translate("WidgetMixer", "Xpos", None))
        self.LabelXposValueText.setText(_translate("WidgetMixer", "0", None))
        self.LabelYposText.setText(_translate("WidgetMixer", "Ypos", None))
        self.LabelYposValueText.setText(_translate("WidgetMixer", "0", None))
        self.LabelFont.setText(_translate("WidgetMixer", "Fuente", None))
        self.LabelTextSize.setText(_translate("WidgetMixer", "Tamaño", None))
        self.LabelStyle.setText(_translate("WidgetMixer", "Estilo", None))
        self.ComboBoxStyle.setItemText(0, _translate("WidgetMixer", "Normal", None))
        self.ComboBoxStyle.setItemText(1, _translate("WidgetMixer", "Negrita", None))
        self.ComboBoxStyle.setItemText(2, _translate("WidgetMixer", "Cursiva", None))
        self.ComboBoxStyle.setItemText(3, _translate("WidgetMixer", "Negrita y Cursiva", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabText), _translate("WidgetMixer", "Texto", None))

